### ISSUE TITLE
signal_shutdown and core dumped

### ISSUE THREAD

**Issue by Shentheman** [personalrobotics/herbpy#46] opened 2015-10-05 05:53 UTC
When I tried to `rosrun` the `console.py` on my Ubuntu, VMWare by doing `roscore` and:
```
rosrun herbpy console.py --sim –viewer=rviz 
OR rosrun herbpy console.py --sim –viewer 
OR rosrun herbpy console.py --sim –viewer=interactivemarker
```

Sometimes it works, but sometimes I ended up with 2 kinds of following errors. What I did was wrong?
1.
```
[ WARN] [1444023961.921101622]: Group 'head_hand' is empty.
[kinbody.cpp:1470 SetDOFValues] dof 4 value is not in limits 0.000000e+00<5.235988e-01
[kinbody.cpp:1470 SetDOFValues] dof 15 value is not in limits 0.000000e+00<5.235988e-01
Traceback (most recent call last):
  File "/home/shen/Research/catkin_ws/src/herbpy/scripts/console.py", line 44, in <module>
    env, robot = herbpy.initialize(**herbpy_args)
  File "/home/shen/Research/catkin_ws/src/herbpy/src/herbpy/herb.py", line 87, in initialize
    prpy.bind_subclass(robot, HERBRobot, **kw_args)
  File "/home/shen/Research/catkin_ws/src/prpy/src/prpy/bind.py", line 366, in bind_subclass
    instance.__init__(*args, **kw_args)
TypeError: __init__() takes exactly 11 arguments (10 given)
[INFO] [rospy.core:core.py:387]:signal_shutdown: signal_shutdown [atexit]
```

2.
```
[WARNING] [root:logger.py:71]:initialize_logging: Install termcolor to colorize log messages.
[ WARN] [1444023690.382634257]: Group 'head_hand' is empty.
[kinbody.cpp:1470 SetDOFValues] dof 4 value is not in limits 0.000000e+00<5.235988e-01
[kinbody.cpp:1470 SetDOFValues] dof 15 value is not in limits 0.000000e+00<5.235988e-01
WARNING: QApplication was not created in the main() thread.
[ INFO] [1444023692.147753289]: Stereo is NOT SUPPORTED
[ INFO] [1444023692.148126118]: OpenGl version: 2.1 (GLSL 1.2).
[INFO] [rospy.core:core.py:387]:signal_shutdown: signal_shutdown [atexit]
Segmentation fault (core dumped)
```

**Comment by jeking04** [comment] 2015-10-05 13:33
This problem is due to the introduction the perception_sim flag that is not getting properly passed in by the console. I thought we fixed this but perhaps it didn't get committed. I can't reproduce it in master, so I think you are probably on a branch. Can you post what branch of herbpy you are on and I will fix it in that branch?

**Comment by Shentheman** [comment] 2015-10-05 14:10
Since I just wanted to try some codes running on herbpy, I think what I did was:
> 
> $ wstool merge https://raw.githubusercontent.com/personalrobotics/pr-rosinstalls/master/herb-minimal-sim.rosinstall
I guess this will download the master version, right? So I don’t think I have my branch now. Do you want me to create one so that you can fix it?

Thank you so much!
Sincerely
Shen Li
_________________

**Comment by jeking04** [comment] 2015-10-05 14:51
Hmm...it looks like master still has the 10 arguments:

https://github.com/personalrobotics/herbpy/blob/master/src/herbpy/herbrobot.py#L26

Can you double check your branch by running the following commands in your workspace:

```
cmd> roscd herbpy
cmd> git branch
```

Thanks,
Jen

**Comment by Shentheman** [comment] 2015-10-05 14:57
Thanks Jen!
It shows: 
> 
> shen@ubuntu:~/Research/catkin_ws/src/herbpy$ git branch
> * block_sorting
>   master
Maybe the block_sorting is not using the master of herbpy? 
I will try to run it again.


Thank you so much!
Sincerely
Shen Li
_________________

**Comment by jeking04** [comment] 2015-10-05 15:09
Okay. Yes, block_sorting is a different branch of herbpy. I will make the fix we need but I am still a bit surprised you see this error using the herbpy console. Can you provide results from the following command:

```
cmd> roscd herbpy
cmd> git status
```

**Comment by Shentheman** [comment] 2015-10-05 15:14
Yeah! Sure.
I modified the console.py but then I changed it back so it would not be the issue I think. I add a test file shen.py also.

> shen@ubuntu:~/Research/catkin_ws/src/herbpy$ git status
> On branch block_sorting
> Your branch is up-to-date with 'origin/block_sorting'.
> 
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
> 	modified:   examples/graspFuzeBottle.py
> 	modified:   scripts/console.py
> 
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
> 
> 	examples/shen.py
> 
> no changes added to commit (use "git add" and/or "git commit -a")


Thank you so much!
Sincerely
Shen Li
_________________

**Comment by jeking04** [comment] 2015-10-05 15:34
Okay, my guess is that if you do a ```git diff scripts/console.py``` you will see that the perception_sim flag got removed at some point during your changes. But we should be robust to that. I have pushed a change that should fix the problem. To get it run the following commands:

```
cmd> roscd herbpy
cmd> git pull
```

**Closed** 2015-10-16 17:34 UTC
