### ISSUE TITLE
Re-initializing within same script not possible due to viewers

### ISSUE THREAD

**Issue by mklingen** [personalrobotics/herbpy#62] opened 2015-11-19 15:07 UTC
@herlant has been saying that when she tries to reinitialize `herbpy` (i.e `herbpy.initialize(...)`) within the same script, then `qtcoin`, `or_rviz`, and `InteractiveMarker` all fail. `qtcoin` and `rviz` throw the error:

```
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
 Extension:    139 (RENDER)
 Minor opcode: 4 (RenderCreatePicture)
 Resource id:  0x3e0002f
X Error: BadWindow (invalid Window parameter) 3
 Major opcode: 2 (X_ChangeWindowAttributes)
 Resource id:  0x3e0002f
```

while InteractiveMarker stops displaying anything.

**Comment by mkoval** [comment] 2015-11-19 17:40
This is a limitation of the `SetViewer` function in OpenRAVE because it relies on global state. We can't do anything about this PrPy - we would need to modify OpenRAVE.

**Comment by mkoval** [comment] 2015-11-19 17:43
Actually, I may be mistaken: it looks like Rosen added support for multiple viewers in https://github.com/rdiankov/openrave/commit/70c15b76784d8f58641daa680158953ec3cef831. It must be a problem in the individual viewers.

**Comment by mklingen** [comment] 2015-11-19 19:43
@herlant which version of OpenRAVE have you been using?

**Comment by herlant** [comment] 2015-11-19 19:49
@mklingen the version that's in github. It's probably also worth noting that I'm using adapy, not herbpy. But presumably the issue is agnostic of which one

**Comment by mklingen** [comment] 2015-11-19 20:21
okay, I was able to replicate the issue. Creating two environments and adding viewers to both of them causes the crash. Its definitely an issue with OpenRAVE, not prpy, as this script causes the problem:

```
env = openravepy.Environment()
env.SetViewer('qtcoin') 

env2 = openravepy.Environment() 
env2.SetViewer('qtcoin') 

import IPython
IPython.embed()
```

**Comment by mklingen** [comment] 2015-11-19 20:24
https://github.com/rdiankov/openrave/issues/377

**Comment by mkoval** [comment] 2016-02-08 22:39
Closing this since it's an issue in OpenRAVE, not `herbpy`.

**Closed by mkoval** 2016-02-08 22:39 UTC
Labels: bug
